/* Auto-generated from prelude.jacl - do not edit */
static const char *jacl_prelude_source =
    "# JACL Prelude - Macro definitions loaded before user code\n"
    "# This file is converted to a C header (prelude_source.h) by build.sh\n"
    "\n"
    "# Lambda shorthand: [\\ + $it 1] expands to proc {^it} { + $it 1 }\n"
    "defmacro \\ {head ..rest} {\n"
    "  def body [make-syntax \"command\" $head $rest]\n"
    "  def blk [make-syntax \"block\" [vec $body]]\n"
    "  def pn [make-syntax \"lit-string-caret\" \"it\"]\n"
    "  def params [make-syntax \"command\" $pn [vec]]\n"
    "  def nm [make-syntax \"lit-string\" \"\"]\n"
    "  [make-syntax \"command\" [make-syntax \"lit-string\" \"proc\"] [vec $nm $params $blk]]\n"
    "}\n"
    "\n"
    "# NOTE: Binding operators (=, :, ::) and the pipe operator (|) used to be\n"
    "# defined here as macros, but the parser already desugars them at parse\n"
    "# time (typed bindings like `i64 x = 5` go through a dedicated rule and\n"
    "# would be MIScompiled if these macros expanded — `lhs` ends up wrapped\n"
    "# in a stray command). Removed 2026-05-18 along with the macro fast-path\n"
    "# fix that started consuming the auto-generated prelude name list — any\n"
    "# entry here triggers expansion at every user call site, so a macro that\n"
    "# can't safely fire must not appear in the file.\n"
    "\n"
    "# Logical AND: [and a b] expands to [&& a b] for short-circuit behavior\n"
    "defmacro and {a b} {\n"
    "  syntax-quote [&& ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical OR: [or a b] expands to [|| a b] for short-circuit behavior\n"
    "defmacro or {a b} {\n"
    "  syntax-quote [|| ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical NOT: [not a] expands to [~ a]\n"
    "# Uses make-syntax because ~ is the unquote operator in syntax-quote\n"
    "defmacro not {a} {\n"
    "  def head [make-syntax \"lit-string\" \"~\"]\n"
    "  [make-syntax \"command\" $head [vec $a]]\n"
    "}\n"
    "\n"
    "# timeout n body — race body against a sleeping branch that errors after n\n"
    "# seconds. Returns body's value if it completes within the deadline,\n"
    "# otherwise an error value with payload \"timeout\".  Requires a suspending\n"
    "# context (the implicit one created by spawn/parallel/race/proc with\n"
    "# suspending callees).\n"
    "defmacro timeout {n body} {\n"
    "  syntax-quote [race ~body { sleep ~n; error \"timeout\" }]\n"
    "}\n"
    ;
