/* Auto-generated from prelude.jacl - do not edit */
static const char *jacl_prelude_source =
    "# JACL Prelude - Macro definitions loaded before user code\n"
    "# This file is converted to a C header (prelude_source.h) by build.sh\n"
    "\n"
    "# Lambda shorthand: [\\ + $it 1] expands to proc {^it} { + $it 1 }\n"
    "defmacro \\ {head ..rest} {\n"
    "  def body [make-syntax \"command\" $head $rest]\n"
    "  def blk [make-syntax \"block\" [vec $body]]\n"
    "  def pn [make-syntax \"lit-string-caret\" \"it\"]\n"
    "  def params [make-syntax \"command\" $pn [vec]]\n"
    "  def nm [make-syntax \"lit-string\" \"\"]\n"
    "  [make-syntax \"command\" [make-syntax \"lit-string\" \"proc\"] [vec $nm $params $blk]]\n"
    "}\n"
    "\n"
    "# Binding operator =: x = 3 expands to [def x 3]\n"
    "# Parser produces [= [x] 3]; macro unwraps zero-arg commands to simple names\n"
    "defmacro = {lhs rhs} {\n"
    "  # Check if lhs is a zero-arg command (bare name from parser)\n"
    "  if [== [syntax-kind $lhs] \"command\"] {\n"
    "    if [== [vec-len [syntax-args $lhs]] 0] {\n"
    "      # Unwrap: [x] -> x\n"
    "      def name [syntax-head $lhs]\n"
    "      syntax-quote [def ~name ~rhs]\n"
    "    } else {\n"
    "      # Multi-arg command: destructuring pattern\n"
    "      syntax-quote [def ~lhs ~rhs]\n"
    "    }\n"
    "  } else {\n"
    "    # Not a command: pass through\n"
    "    syntax-quote [def ~lhs ~rhs]\n"
    "  }\n"
    "}\n"
    "\n"
    "# Mutable binding operator :: x : 0 expands to [mut x 0]\n"
    "defmacro : {lhs rhs} {\n"
    "  if [== [syntax-kind $lhs] \"command\"] {\n"
    "    if [== [vec-len [syntax-args $lhs]] 0] {\n"
    "      def name [syntax-head $lhs]\n"
    "      syntax-quote [mut ~name ~rhs]\n"
    "    } else {\n"
    "      syntax-quote [mut ~lhs ~rhs]\n"
    "    }\n"
    "  } else {\n"
    "    syntax-quote [mut ~lhs ~rhs]\n"
    "  }\n"
    "}\n"
    "\n"
    "# Pipe operator: foo a | bar b expands to [bar [foo a] b]\n"
    "# Threads lhs as first argument to rhs command\n"
    "defmacro | {lhs rhs} {\n"
    "  if [== [syntax-kind $rhs] \"command\"] {\n"
    "    def head [syntax-head $rhs]\n"
    "    def args [syntax-args $rhs]\n"
    "    def new-args [vec-concat [vec $lhs] $args]\n"
    "    [make-syntax \"command\" $head $new-args]\n"
    "  } else {\n"
    "    syntax-error \"pipe operator | requires a command on the right side\"\n"
    "  }\n"
    "}\n"
    "\n"
    "# Logical AND: [and a b] expands to [&& a b] for short-circuit behavior\n"
    "defmacro and {a b} {\n"
    "  syntax-quote [&& ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical OR: [or a b] expands to [|| a b] for short-circuit behavior\n"
    "defmacro or {a b} {\n"
    "  syntax-quote [|| ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical NOT: [not a] expands to [~ a]\n"
    "# Uses make-syntax because ~ is the unquote operator in syntax-quote\n"
    "defmacro not {a} {\n"
    "  def head [make-syntax \"lit-string\" \"~\"]\n"
    "  [make-syntax \"command\" $head [vec $a]]\n"
    "}\n"
    "\n"
    "# Reassignment operator ::: x :: 5 expands to [set x 5]\n"
    "defmacro :: {lhs rhs} {\n"
    "  if [== [syntax-kind $lhs] \"command\"] {\n"
    "    if [== [vec-len [syntax-args $lhs]] 0] {\n"
    "      def name [syntax-head $lhs]\n"
    "      syntax-quote [set ~name ~rhs]\n"
    "    } else {\n"
    "      syntax-quote [set ~lhs ~rhs]\n"
    "    }\n"
    "  } else {\n"
    "    syntax-quote [set ~lhs ~rhs]\n"
    "  }\n"
    "}\n"
    ;
