/* Auto-generated from prelude.jacl - do not edit */
static const char *jacl_prelude_source =
    "# JACL Prelude - Macro definitions loaded before user code\n"
    "# This file is converted to a C header (prelude_source.h) by build.sh\n"
    "\n"
    "# Lambda shorthand: [\\ + $it 1] expands to proc {^it} { + $it 1 }\n"
    "defmacro \\ {head ..rest} {\n"
    "  def body [make-syntax \"command\" $head $rest]\n"
    "  def blk [make-syntax \"block\" [vec $body]]\n"
    "  def pn [make-syntax \"lit-string-caret\" \"it\"]\n"
    "  def params [make-syntax \"command\" $pn [vec]]\n"
    "  def nm [make-syntax \"lit-string\" \"\"]\n"
    "  [make-syntax \"command\" [make-syntax \"lit-string\" \"proc\"] [vec $nm $params $blk]]\n"
    "}\n"
    "\n"
    "# NOTE: Binding operators (=, :, ::) and the pipe operator (|) used to be\n"
    "# defined here as macros, but the parser already desugars them at parse\n"
    "# time (typed bindings like `i64 x = 5` go through a dedicated rule and\n"
    "# would be MIScompiled if these macros expanded — `lhs` ends up wrapped\n"
    "# in a stray command). Removed 2026-05-18 along with the macro fast-path\n"
    "# fix that started consuming the auto-generated prelude name list — any\n"
    "# entry here triggers expansion at every user call site, so a macro that\n"
    "# can't safely fire must not appear in the file.\n"
    "\n"
    "# Logical AND: [and a b] expands to [&& a b] for short-circuit behavior\n"
    "defmacro and {a b} {\n"
    "  syntax-quote [&& ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical OR: [or a b] expands to [|| a b] for short-circuit behavior\n"
    "defmacro or {a b} {\n"
    "  syntax-quote [|| ~a ~b]\n"
    "}\n"
    "\n"
    "# Logical NOT: [not a] expands to [~ a]\n"
    "# Uses make-syntax because ~ is the unquote operator in syntax-quote\n"
    "defmacro not {a} {\n"
    "  def head [make-syntax \"lit-string\" \"~\"]\n"
    "  [make-syntax \"command\" $head [vec $a]]\n"
    "}\n"
    "\n"
    "# incr name — increment a mutable binding in place: [incr i] == [set i [+ $i 1]]\n"
    "# Sugar for the common counted-loop step expression. Named `incr` rather\n"
    "# than `inc` since `inc` is widely used as a user-defined proc name across\n"
    "# the test suite; the prelude must not shadow that.\n"
    "#\n"
    "# The macro takes a bare name (lit-string syntax) for the set target, then\n"
    "# builds a fresh var-ref to that same name for the `+` operand — `syntax-\n"
    "# datum` pulls the string out of the lit-string syntax node, and\n"
    "# `make-syntax \"var-ref\"` rebuilds it as a var-ref.\n"
    "defmacro incr {x} {\n"
    "  def name [syntax-datum $x]\n"
    "  def vref [make-syntax \"var-ref\" $name]\n"
    "  syntax-quote [set ~x [+ ~vref 1]]\n"
    "}\n"
    "\n"
    "# timeout n body — race body against a sleeping branch that errors after n\n"
    "# seconds. Returns body's value if it completes within the deadline,\n"
    "# otherwise an error value with payload \"timeout\".  Requires a suspending\n"
    "# context (the implicit one created by spawn/parallel/race/proc with\n"
    "# suspending callees).\n"
    "defmacro timeout {n body} {\n"
    "  syntax-quote [race ~body { sleep ~n; error \"timeout\" }]\n"
    "}\n"
    "\n"
    "# assert — predicate check; on failure, format a source-context message\n"
    "# and call panic.\n"
    "#\n"
    "# Two forms:\n"
    "#   [assert EXPR]            single arg; halt if EXPR is falsy.\n"
    "#   [assert OP arg1 arg2..]  predicate form; evaluate [OP arg1 ..] and\n"
    "#                            halt if the result is falsy.\n"
    "#\n"
    "# The predicate form is the natural replacement for the old infix\n"
    "# `assert ($a == 7)` once `()` is gone: write `assert == $a 7`.\n"
    "#\n"
    "# Expansion:\n"
    "#   [if <pred> {} { panic \"assertion failed: <source>\" }]\n"
    "# where <source> is the syntax-str of the original predicate, captured\n"
    "# at macro-expansion time. `panic` halts unconditionally.\n"
    "defmacro assert {head ..rest} {\n"
    "  if [== [vec-len $rest] 0] {\n"
    "    # Single-arg form: $head is the expression to test for truthiness.\n"
    "    def msg-str [concat \"assertion failed: \" [syntax-str $head]]\n"
    "    def msg [make-syntax \"lit-string\" $msg-str]\n"
    "    syntax-quote [if ~head {} { panic ~msg }]\n"
    "  } {\n"
    "    # Predicate form: $head is the operator, $rest collects its operands.\n"
    "    def pred [make-syntax \"command\" $head $rest]\n"
    "    def msg-str [concat \"assertion failed: \" [syntax-str $pred]]\n"
    "    def msg [make-syntax \"lit-string\" $msg-str]\n"
    "    syntax-quote [if ~pred {} { panic ~msg }]\n"
    "  }\n"
    "}\n"
    ;
